import { describe, expect, it } from "vitest";
import { bitbucketPipelines, ciProviderFor, gitlabCi } from "./ci.js";

const base = { target: "prod", nodeVersion: "24", branch: "main", secrets: [] as string[] };
const gitlabRegistry = { host: "registry.gitlab.com", usernameEnv: "REGISTRY_USERNAME", passwordEnv: "REGISTRY_PASSWORD" };
const otherRegistry = { host: "ghcr.io", usernameEnv: "REGISTRY_USERNAME", passwordEnv: "REGISTRY_PASSWORD" };
const DOCKER_CLI =
  "curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-27.3.1.tgz | tar -xz --strip-components=1 -C /usr/local/bin docker/docker";

describe("gitlabCi.render", () => {
  it("is registered, and writes .gitlab-ci.yml", () => {
    expect(ciProviderFor("gitlab")).toBe(gitlabCi);
    expect(gitlabCi.filePath).toBe(".gitlab-ci.yml");
  });

  it("renders the pnpm + Docker job for GitLab's own registry (golden)", () => {
    expect(gitlabCi.render({ ...base, packageManager: "pnpm", docker: true, registry: gitlabRegistry })).toBe(`# Generated by \`blix deploy ci gitlab\`. The pipeline logic lives in \`blix deploy\`, so
# running it locally and running it here do exactly the same thing.
deploy:
  stage: deploy
  image: node:24
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    REGISTRY_USERNAME: $CI_REGISTRY_USER
    REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  before_script:
    - ${DOCKER_CLI}
    - corepack enable
  script:
    - pnpm install --frozen-lockfile
    - pnpm exec blix deploy prod
`);
  });

  it("renders a Vercel job with no Docker service, and lists the variables to set (golden)", () => {
    expect(
      gitlabCi.render({ ...base, packageManager: "npm", docker: false, registry: undefined, secrets: ["VERCEL_TOKEN", "VERCEL_ORG_ID", "VERCEL_PROJECT_ID"] }),
    ).toBe(`# Generated by \`blix deploy ci gitlab\`. The pipeline logic lives in \`blix deploy\`, so
# running it locally and running it here do exactly the same thing.
#
# Set these as masked CI/CD variables (Settings > CI/CD > Variables):
#   VERCEL_TOKEN
#   VERCEL_ORG_ID
#   VERCEL_PROJECT_ID
deploy:
  stage: deploy
  image: node:24
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - npm ci
    - npx blix deploy prod
`);
  });

  it("asks for credentials as CI/CD variables when the registry isn't GitLab's", () => {
    const yaml = gitlabCi.render({ ...base, packageManager: "npm", docker: true, registry: otherRegistry });

    expect(yaml).toContain("#   REGISTRY_USERNAME");
    expect(yaml).toContain("#   REGISTRY_PASSWORD");
    expect(yaml).not.toContain("$CI_REGISTRY_USER");
  });

  it("does not list a registry credential twice when the target also requires it", () => {
    const yaml = gitlabCi.render({ ...base, packageManager: "npm", docker: true, registry: otherRegistry, secrets: ["REGISTRY_PASSWORD", "FLY_API_TOKEN"] });

    expect(yaml.match(/#   REGISTRY_PASSWORD/g)).toHaveLength(1);
    expect(yaml).toContain("#   FLY_API_TOKEN");
  });

  it.each([
    ["pnpm", ["corepack enable"], "pnpm install --frozen-lockfile", "pnpm exec blix deploy prod"],
    ["npm", [], "npm ci", "npx blix deploy prod"],
    ["yarn", ["corepack enable"], "yarn install --frozen-lockfile", "yarn blix deploy prod"],
    ["bun", ["npm install -g bun"], "bun install --frozen-lockfile", "bunx blix deploy prod"],
  ] as const)("%s uses its own prepare, install and exec lines", (packageManager, prepare, install, exec) => {
    const yaml = gitlabCi.render({ ...base, packageManager, docker: false, registry: undefined });

    for (const line of prepare) {
      expect(yaml).toContain(`    - ${line}`);
    }
    expect(yaml).toContain(`    - ${install}`);
    expect(yaml).toContain(`    - ${exec}`);
    expect(yaml.includes("before_script") === prepare.length > 0).toBe(true);
  });

  it("uses the given branch and node version", () => {
    const yaml = gitlabCi.render({ ...base, packageManager: "npm", docker: false, registry: undefined, branch: "release", nodeVersion: "26" });

    expect(yaml).toContain('- if: $CI_COMMIT_BRANCH == "release"');
    expect(yaml).toContain("image: node:26");
  });
});

describe("bitbucketPipelines.render", () => {
  it("is registered, and writes bitbucket-pipelines.yml", () => {
    expect(ciProviderFor("bitbucket")).toBe(bitbucketPipelines);
    expect(bitbucketPipelines.filePath).toBe("bitbucket-pipelines.yml");
  });

  it("renders the pnpm + Docker pipeline (golden)", () => {
    expect(bitbucketPipelines.render({ ...base, packageManager: "pnpm", docker: true, registry: otherRegistry })).toBe(`# Generated by \`blix deploy ci bitbucket\`. The pipeline logic lives in \`blix deploy\`, so
# running it locally and running it here do exactly the same thing.
#
# Set these as secured repository variables (Repository settings > Pipelines > Repository variables):
#   REGISTRY_USERNAME
#   REGISTRY_PASSWORD
image: node:24

pipelines:
  branches:
    main:
      - step:
          name: Deploy prod
          services:
            - docker
          script:
            - command -v docker > /dev/null || (${DOCKER_CLI})
            - corepack enable
            - pnpm install --frozen-lockfile
            - pnpm exec blix deploy prod
`);
  });

  it("renders a Netlify pipeline with no Docker service (golden)", () => {
    expect(
      bitbucketPipelines.render({ ...base, packageManager: "npm", docker: false, registry: undefined, secrets: ["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"] }),
    ).toBe(`# Generated by \`blix deploy ci bitbucket\`. The pipeline logic lives in \`blix deploy\`, so
# running it locally and running it here do exactly the same thing.
#
# Set these as secured repository variables (Repository settings > Pipelines > Repository variables):
#   NETLIFY_AUTH_TOKEN
#   NETLIFY_SITE_ID
image: node:24

pipelines:
  branches:
    main:
      - step:
          name: Deploy prod
          script:
            - npm ci
            - npx blix deploy prod
`);
  });

  it("uses the given branch and target name", () => {
    const yaml = bitbucketPipelines.render({ ...base, packageManager: "npm", docker: false, registry: undefined, branch: "release", target: "staging" });

    expect(yaml).toContain("    release:");
    expect(yaml).toContain("name: Deploy staging");
    expect(yaml).toContain("npx blix deploy staging");
  });

  it("never lists a credential twice", () => {
    const yaml = bitbucketPipelines.render({ ...base, packageManager: "npm", docker: true, registry: otherRegistry, secrets: ["REGISTRY_USERNAME", "X"] });

    expect(yaml.match(/#   REGISTRY_USERNAME/g)).toHaveLength(1);
  });
});
