import { describe, expect, it } from "vitest";
import { CI_PROVIDER_IDS, ciProviderFor, githubActions } from "./ci.js";

const base = { target: "prod", nodeVersion: "24", branch: "main", secrets: [] as string[], docker: false };

describe("githubActions.render", () => {
  it("renders the full pnpm workflow for ghcr.io (golden)", () => {
    const yaml = githubActions.render({
      ...base,
      docker: true,
      packageManager: "pnpm",
      registry: { host: "ghcr.io", usernameEnv: "REGISTRY_USERNAME", passwordEnv: "REGISTRY_PASSWORD" },
    });

    expect(yaml).toBe(`# Generated by \`blix deploy ci github\`. The pipeline logic lives in \`blix deploy\`, so
# running it locally and running it here do exactly the same thing.
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deploy-\${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec blix deploy prod
        env:
          REGISTRY_USERNAME: \${{ github.actor }}
          REGISTRY_PASSWORD: \${{ secrets.GITHUB_TOKEN }}
`);
  });

  it("uses repository secrets for any other registry, and no packages permission", () => {
    const yaml = githubActions.render({
      ...base,
      packageManager: "npm",
      registry: { host: "docker.io", usernameEnv: "DOCKER_USER", passwordEnv: "DOCKER_TOKEN" },
    });

    expect(yaml).toContain("DOCKER_USER: ${{ secrets.DOCKER_USER }}");
    expect(yaml).toContain("DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}");
    expect(yaml).not.toContain("packages: write");
    expect(yaml).not.toContain("github.actor");
  });

  it("passes extra required variables through as secrets, without duplicating registry ones", () => {
    const yaml = githubActions.render({
      ...base,
      packageManager: "npm",
      secrets: ["FLY_API_TOKEN", "REGISTRY_PASSWORD"],
      registry: { host: "ghcr.io", usernameEnv: "REGISTRY_USERNAME", passwordEnv: "REGISTRY_PASSWORD" },
    });

    expect(yaml).toContain("FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}");
    expect(yaml.match(/REGISTRY_PASSWORD:/g)).toHaveLength(1);
  });

  it("omits the env block when there is nothing to pass", () => {
    const yaml = githubActions.render({ ...base, packageManager: "npm", registry: undefined });

    expect(yaml).not.toContain("env:");
    expect(yaml.trimEnd().endsWith("- run: npx blix deploy prod")).toBe(true);
  });

  it.each([
    ["pnpm", "pnpm exec blix deploy prod", "pnpm install --frozen-lockfile", "cache: pnpm"],
    ["npm", "npx blix deploy prod", "npm ci", "cache: npm"],
    ["yarn", "yarn blix deploy prod", "yarn install --frozen-lockfile", "cache: yarn"],
    ["bun", "bunx blix deploy prod", "bun install --frozen-lockfile", "oven-sh/setup-bun@v2"],
  ] as const)("%s uses its own install and exec commands", (packageManager, exec, install, extra) => {
    const yaml = githubActions.render({ ...base, packageManager, registry: undefined });

    expect(yaml).toContain(`- run: ${exec}`);
    expect(yaml).toContain(`- run: ${install}`);
    expect(yaml).toContain(extra);
  });

  it("uses the given branch and node version", () => {
    const yaml = githubActions.render({ ...base, packageManager: "npm", branch: "release", nodeVersion: "26", registry: undefined });

    expect(yaml).toContain("branches: [release]");
    expect(yaml).toContain("node-version: 26");
  });
});

describe("ciProviderFor", () => {
  it("knows github, gitlab and bitbucket", () => {
    expect(ciProviderFor("github")).toBe(githubActions);
    expect(CI_PROVIDER_IDS).toEqual(["github", "gitlab", "bitbucket"]);
  });

  it("returns undefined for an unknown provider", () => {
    expect(ciProviderFor("travis")).toBeUndefined();
  });
});
