import type { PackageManager } from "@blixis-io/cli";

export interface CiRenderOptions {
  target: string;
  packageManager: PackageManager;
  nodeVersion: string;
  /** Branch whose pushes deploy. */
  branch: string;
  /** Environment variable names to pass through from the CI secret store. */
  secrets: readonly string[];
  registry?: { host: string; usernameEnv: string; passwordEnv: string } | undefined;
  /** Whether the deploy runs `docker`. GitHub's runners include it; GitLab and Bitbucket need a daemon (and the CLI) added. */
  docker: boolean;
}

/** One CI system. Adding another means adding a provider here and to `PROVIDERS`. */
export interface CiProvider {
  id: string;
  label: string;
  /** Where the generated file goes, relative to the project root. */
  filePath: string;
  render(options: CiRenderOptions): string;
}

const SETUP: Record<PackageManager, { actions: string[]; cache: string; install: string; exec: string }> = {
  pnpm: { actions: ["      - uses: pnpm/action-setup@v4"], cache: "pnpm", install: "pnpm install --frozen-lockfile", exec: "pnpm exec" },
  npm: { actions: [], cache: "npm", install: "npm ci", exec: "npx" },
  yarn: { actions: [], cache: "yarn", install: "yarn install --frozen-lockfile", exec: "yarn" },
  bun: { actions: ["      - uses: oven-sh/setup-bun@v2"], cache: "", install: "bun install --frozen-lockfile", exec: "bunx" },
};

const GHCR = "ghcr.io";

export const githubActions: CiProvider = {
  id: "github",
  label: "GitHub Actions",
  filePath: ".github/workflows/deploy.yml",

  render({ target, packageManager, nodeVersion, branch, secrets, registry }) {
    const setup = SETUP[packageManager];
    const usesGhcr = registry?.host === GHCR;

    // GitHub already provides credentials for its own registry; anything else comes from repo secrets.
    const env: [string, string][] = [];
    if (registry) {
      env.push(
        [registry.usernameEnv, usesGhcr ? "${{ github.actor }}" : `\${{ secrets.${registry.usernameEnv} }}`],
        [registry.passwordEnv, usesGhcr ? "${{ secrets.GITHUB_TOKEN }}" : `\${{ secrets.${registry.passwordEnv} }}`],
      );
    }
    for (const name of secrets) {
      if (!env.some(([key]) => key === name)) {
        env.push([name, `\${{ secrets.${name} }}`]);
      }
    }

    const nodeStep = [
      "      - uses: actions/setup-node@v6",
      "        with:",
      `          node-version: ${nodeVersion}`,
      ...(setup.cache ? [`          cache: ${setup.cache}`] : []),
    ];

    return `# Generated by \`blix deploy ci github\`. The pipeline logic lives in \`blix deploy\`, so
# running it locally and running it here do exactly the same thing.
name: Deploy

on:
  push:
    branches: [${branch}]
  workflow_dispatch:

concurrency:
  group: deploy-\${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read${usesGhcr ? "\n      packages: write" : ""}
    steps:
      - uses: actions/checkout@v4
${[...setup.actions, ...nodeStep].join("\n")}
      - run: ${setup.install}
      - run: ${setup.exec} blix deploy ${target}${
        env.length > 0
          ? `\n        env:\n${env.map(([key, value]) => `          ${key}: ${value}`).join("\n")}`
          : ""
      }
`;
  },
};

/** What a container-based CI job runs for each package manager, in a plain `node` image. */
const SCRIPT: Record<PackageManager, { prepare: string[]; install: string; exec: string }> = {
  pnpm: { prepare: ["corepack enable"], install: "pnpm install --frozen-lockfile", exec: "pnpm exec" },
  npm: { prepare: [], install: "npm ci", exec: "npx" },
  yarn: { prepare: ["corepack enable"], install: "yarn install --frozen-lockfile", exec: "yarn" },
  bun: { prepare: ["npm install -g bun"], install: "bun install --frozen-lockfile", exec: "bunx" },
};

const DOCKER_VERSION = "27.3.1";

/** The static Docker CLI, for images (like `node`) that don't include one. Only the client: the daemon is a CI service. */
const INSTALL_DOCKER_CLI = `curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz | tar -xz --strip-components=1 -C /usr/local/bin docker/docker`;

const GITLAB_REGISTRY = "registry.gitlab.com";

const comment = (secrets: readonly string[], where: string): string[] =>
  secrets.length === 0 ? [] : ["#", `# Set these ${where}:`, ...secrets.map((name) => `#   ${name}`)];

export const gitlabCi: CiProvider = {
  id: "gitlab",
  label: "GitLab CI",
  filePath: ".gitlab-ci.yml",

  render({ target, packageManager, nodeVersion, branch, secrets, registry, docker }) {
    const { prepare, install, exec } = SCRIPT[packageManager];
    const usesGitlabRegistry = registry?.host === GITLAB_REGISTRY;

    // GitLab provides credentials for its own registry; any other registry reads the variables you set.
    const variables: string[] = [
      ...(docker ? ['    DOCKER_HOST: tcp://docker:2375', '    DOCKER_TLS_CERTDIR: ""'] : []),
      ...(registry && usesGitlabRegistry
        ? [`    ${registry.usernameEnv}: $CI_REGISTRY_USER`, `    ${registry.passwordEnv}: $CI_REGISTRY_PASSWORD`]
        : []),
    ];
    const needed = [
      ...(registry && !usesGitlabRegistry ? [registry.usernameEnv, registry.passwordEnv] : []),
      ...secrets.filter((name) => name !== registry?.usernameEnv && name !== registry?.passwordEnv),
    ];
    const beforeScript = [...(docker ? [INSTALL_DOCKER_CLI] : []), ...prepare];

    return [
      "# Generated by `blix deploy ci gitlab`. The pipeline logic lives in `blix deploy`, so",
      "# running it locally and running it here do exactly the same thing.",
      ...comment(needed, "as masked CI/CD variables (Settings > CI/CD > Variables)"),
      "deploy:",
      "  stage: deploy",
      `  image: node:${nodeVersion}`,
      "  rules:",
      `    - if: $CI_COMMIT_BRANCH == "${branch}"`,
      ...(docker ? ["  services:", `    - docker:${DOCKER_VERSION.split(".")[0]}-dind`] : []),
      ...(variables.length > 0 ? ["  variables:", ...variables] : []),
      ...(beforeScript.length > 0 ? ["  before_script:", ...beforeScript.map((line) => `    - ${line}`)] : []),
      "  script:",
      `    - ${install}`,
      `    - ${exec} blix deploy ${target}`,
      "",
    ].join("\n");
  },
};

export const bitbucketPipelines: CiProvider = {
  id: "bitbucket",
  label: "Bitbucket Pipelines",
  filePath: "bitbucket-pipelines.yml",

  render({ target, packageManager, nodeVersion, branch, secrets, registry, docker }) {
    const { prepare, install, exec } = SCRIPT[packageManager];
    const needed = [
      ...(registry ? [registry.usernameEnv, registry.passwordEnv] : []),
      ...secrets.filter((name) => name !== registry?.usernameEnv && name !== registry?.passwordEnv),
    ];
    // With the docker service Bitbucket normally provides the CLI; installing it only when missing makes that not matter.
    const dockerCli = docker ? [`command -v docker > /dev/null || (${INSTALL_DOCKER_CLI})`] : [];

    return [
      "# Generated by `blix deploy ci bitbucket`. The pipeline logic lives in `blix deploy`, so",
      "# running it locally and running it here do exactly the same thing.",
      ...comment(needed, "as secured repository variables (Repository settings > Pipelines > Repository variables)"),
      `image: node:${nodeVersion}`,
      "",
      "pipelines:",
      "  branches:",
      `    ${branch}:`,
      "      - step:",
      `          name: Deploy ${target}`,
      ...(docker ? ["          services:", "            - docker"] : []),
      "          script:",
      ...[...dockerCli, ...prepare, install, `${exec} blix deploy ${target}`].map((line) => `            - ${line}`),
      "",
    ].join("\n");
  },
};

const PROVIDERS: Record<string, CiProvider> = {
  [githubActions.id]: githubActions,
  [gitlabCi.id]: gitlabCi,
  [bitbucketPipelines.id]: bitbucketPipelines,
};

export const CI_PROVIDER_IDS = Object.keys(PROVIDERS);

export function ciProviderFor(id: string): CiProvider | undefined {
  return PROVIDERS[id];
}
