import type { PackageManager } from "@blixis-io/cli";

export interface CiRenderOptions {
  target: string;
  packageManager: PackageManager;
  nodeVersion: string;
  /** Branch whose pushes deploy. */
  branch: string;
  /** Environment variable names to pass through from the CI secret store. */
  secrets: readonly string[];
  registry?: { host: string; usernameEnv: string; passwordEnv: string } | undefined;
}

/** One CI system. Adding GitLab CI or Bitbucket Pipelines means adding a provider here. */
export interface CiProvider {
  id: string;
  label: string;
  /** Where the generated file goes, relative to the project root. */
  filePath: string;
  render(options: CiRenderOptions): string;
}

const SETUP: Record<PackageManager, { actions: string[]; cache: string; install: string; exec: string }> = {
  pnpm: { actions: ["      - uses: pnpm/action-setup@v4"], cache: "pnpm", install: "pnpm install --frozen-lockfile", exec: "pnpm exec" },
  npm: { actions: [], cache: "npm", install: "npm ci", exec: "npx" },
  yarn: { actions: [], cache: "yarn", install: "yarn install --frozen-lockfile", exec: "yarn" },
  bun: { actions: ["      - uses: oven-sh/setup-bun@v2"], cache: "", install: "bun install --frozen-lockfile", exec: "bunx" },
};

const GHCR = "ghcr.io";

export const githubActions: CiProvider = {
  id: "github",
  label: "GitHub Actions",
  filePath: ".github/workflows/deploy.yml",

  render({ target, packageManager, nodeVersion, branch, secrets, registry }) {
    const setup = SETUP[packageManager];
    const usesGhcr = registry?.host === GHCR;

    // GitHub already provides credentials for its own registry; anything else comes from repo secrets.
    const env: [string, string][] = [];
    if (registry) {
      env.push(
        [registry.usernameEnv, usesGhcr ? "${{ github.actor }}" : `\${{ secrets.${registry.usernameEnv} }}`],
        [registry.passwordEnv, usesGhcr ? "${{ secrets.GITHUB_TOKEN }}" : `\${{ secrets.${registry.passwordEnv} }}`],
      );
    }
    for (const name of secrets) {
      if (!env.some(([key]) => key === name)) {
        env.push([name, `\${{ secrets.${name} }}`]);
      }
    }

    const nodeStep = [
      "      - uses: actions/setup-node@v6",
      "        with:",
      `          node-version: ${nodeVersion}`,
      ...(setup.cache ? [`          cache: ${setup.cache}`] : []),
    ];

    return `# Generated by \`blix deploy ci github\`. The pipeline logic lives in \`blix deploy\`, so
# running it locally and running it here do exactly the same thing.
name: Deploy

on:
  push:
    branches: [${branch}]
  workflow_dispatch:

concurrency:
  group: deploy-\${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read${usesGhcr ? "\n      packages: write" : ""}
    steps:
      - uses: actions/checkout@v4
${[...setup.actions, ...nodeStep].join("\n")}
      - run: ${setup.install}
      - run: ${setup.exec} blix deploy ${target}${
        env.length > 0
          ? `\n        env:\n${env.map(([key, value]) => `          ${key}: ${value}`).join("\n")}`
          : ""
      }
`;
  },
};

const PROVIDERS: Record<string, CiProvider> = { [githubActions.id]: githubActions };

export const CI_PROVIDER_IDS = Object.keys(PROVIDERS);

export function ciProviderFor(id: string): CiProvider | undefined {
  return PROVIDERS[id];
}
